### ISSUE TITLE
How to format config.json

### ISSUE THREAD

**Issue by mayribeiro** [floraison/flor#19]
```js
{
  "env": "quickstart",
  "domain": "quickstart",
  "log_out": "var/log",
  "flor_debug": "stdout, dbg",
  "sto_uri": "(if == ruby_platform 'java'\n\"jdbc:sqlite://$(root)/var/flor.db\"\n\"sqlite://$(root)/var/flor.db\")",
  "sto_migration_check": false,
  "sto_sync": true,
  "sto_connection_validation": false
}
```

This is correct?

**Comment by jmettraux** [comment]
Hello,

it looks more like:
```js
{
  env: 'quickstart'
  domain: 'quickstart'
  log_out: 'var/log'
  flor_debug: 'stdout,dbg'
  sto_uri: (ife
    == ruby_platform 'java'
    "jdbc:sqlite://$(root)/var/flor.db"
    "sqlite://$(root)/var/flor.db")
  sto_migration_check: false
  sto_sync: true
  sto_connection_validation: false
}
```
(following [quickstart/flor/etc/conf.json](https://github.com/floraison/flor/blob/4900b37a186b816d1740de8eb2743b148221988a/quickstart/flor/etc/conf.json))

If the `ife` construct for `sto_uri:` is too disturbing (for your or your favourite text editor in JSON mode), you can simplify it to:
```js
{
  // ...
  sto_uri: "sqlite://$(root)/var/flor.db"
  // ...
}
```
Assuming that you are not using JRuby but a regular Ruby.

If you have any other question, feel free to ask. Best regards.

**Comment by jmettraux** [comment]
Closing. Best regards.
